version: 0.0
os: linux
files:
  - source: app
    destination: /home/ubuntu/iot_backend_deploy/app
  - source: scripts/
    destination: /home/ubuntu/iot_backend_deploy/scripts/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/build_application.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ubuntu
