version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21
    commands:
      - echo "Instalando dependencias..."
      - go mod tidy
  build:
    commands:
      - echo "Compilando aplicación Go..."
      - go build -o app main.go
  test:
    commands:
      - echo "Ejecutando tests unitarios..."
      - go test ./...
artifacts:
  files:
    - app
    - appspec.yml
    - scripts/**
  discard-paths: no
