version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21
  pre_build:
    commands:
      - echo "Starting pre-build phase"
      - aws --version
      - go version
  build:
    commands:
      - echo "Starting build phase"
      - go mod tidy
      - go build -o app main.go
      - echo "Build completed"
      - ls -la app
      - file app
  post_build:
    commands:
      - echo "Starting post-build phase"
      - ls -la
      - if [ -f app ]; then echo "app file exists"; else echo "ERROR: app file missing"; fi

artifacts:
  files:
    - app
    - appspec.yml
    - scripts/**/*
    - init_users.sql
    - main.go
    - go.mod
    - go.sum
