version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21
    commands:
      - echo "Instalando dependencias..."
      - go mod tidy
  build:
    commands:
      - echo "Compilando aplicación Go..."
      - go build -o app main.go
  post_build:
    commands:
      - echo "Verificando archivo app..."
      - ls -la app
      - echo "Listando todos los archivos para artifacts..."
      - ls -la
      - echo "Verificando archivos específicos de artifacts..."
      - ls -la app appspec.yml scripts/ init_users.sql 2>/dev/null || echo "Algunos archivos de artifacts no encontrados"
      - echo "Verificando estructura de directorios para artifacts..."
      - find . -name "app" -o -name "appspec.yml" -o -name "init_users.sql" -o -name "scripts"
      - echo "Ejecutando tests unitarios..."
      - go test ./...
artifacts:
  files:
    - app
    - appspec.yml
    - scripts/**/*
    - init_users.sql
  base-directory: .
  name: iot-backend-artifacts
