version: "3.8"

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - iot-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iot-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./init_users.sql:/app/init_users.sql
    entrypoint: ["sh", "-c", "sqlite3 /app/users.db < /app/init_users.sql && exec ./app"]
    depends_on:
      - mqtt
    networks:
      - iot-net

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - iot-net

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - iot-net
    depends_on:
      - prometheus

volumes:
  grafana-data:

networks:
  iot-net:
    driver: bridge
